# rules.mk
# MCU = STM32F401
# MCU = RP2040
# BOOTLOADER = rp2040

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes

CONSOLE_ENABLE = yes
# COMMAND_ENABLE = yes

# SPI_DRIVER_ENABLE = yes
# ENCODER_ENABLE = yes
# SPI_DRIVER_REQUIRED = yes
# I2C_DRIVER_REQUIRED = yes
# I2C_ENABLE = yes
# OPT_DEFS += -DHAL_USE_I2C=TRUE
# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = pimoroni_trackball
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
ENCODER_ENABLE = yes
# MOUSEKEY_ENABLE = yes
# ENCODER_RESOLUTION = 2
WS2812_DRIVER = vendor
RGBLIGHT_ENABLE = yes
# RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_ENABLE = WS2812

# SERIAL_ENABLE = yes
# SPLIT_KEYBOARD = yes
# SERIAL_DRIVER = vendor

RAW_ENABLE = yes