# rules.mk
MCU = RP2040
BOOTLOADER = rp2040
# MCU = STM32F411
# BOOTLOADER = stm32-dfu

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
NKRO_ENABLE = yes
MIDI_ENABLE = no
SERIAL_ENABLE = no
STENO_ENABLE = no

CONSOLE_ENABLE = no
# COMMAND_ENABLE = yes

# SPI_DRIVER_ENABLE = yes
# ENCODER_ENABLE = yes
# SPI_DRIVER_REQUIRED = yes
I2C_DRIVER_REQUIRED = yes
I2C_ENABLE = yes
# RGB_MATRIX_DRIVER = is31fl3741
# OPT_DEFS += -DHAL_USE_I2C=TRUE
# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = pimoroni_trackball
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
ENCODER_ENABLE = yes
# MOUSEKEY_ENABLE = yes
# ENCODER_RESOLUTION = 2
# WS2812_DRIVER = vendor
# RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_ENABLE = WS2812

# SERIAL_ENABLE = yes
# SPLIT_KEYBOARD = yes
# SERIAL_DRIVER = vendor

RAW_ENABLE = yes

# CUSTOM_MATRIX = yes