# rules.mk
# SPI_DRIVER_ENABLE = yes
# ENCODER_ENABLE = yes
# SPI_DRIVER_REQUIRED = yes
# I2C_DRIVER_REQUIRED = yes
# I2C_ENABLE = yes
# OPT_DEFS += -DHAL_USE_I2C=TRUE
# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = pimoroni_trackball
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
CONSOLE_ENABLE = yes
ENCODER_ENABLE = yes
# MOUSEKEY_ENABLE = yes
# ENCODER_RESOLUTION = 2
